### ISSUE TITLE
Unable to create new exercise on Android and Windows 10/EDGE

### ISSUE THREAD

**Issue by llaske** [manki11/ExerciserReact#10]
On Android and on Windows 10 EDGE browser, it's impossible to create a new exercise using type List or Cloze template (MCQ works).
The beginning of Exercise creation works well but once the button Finish is clicked, the new exercise disappears from the exercises list.
Everything works well on Chrome, Firefox or Safari.
It look like there is something wrong about routing. Here's the URL of the activity after creation of new Exercice (all standard arguments disappeared):

On Windows 10:

`http://192.168.1.9:8080/activities/Exerciser.activity/index.html?answer-0=6&answer-1=5&answer-2=3&answer-3=0`

On Android:

`file:///android_asset/www/activities/Exerciser.activity/index.html?answer-0=12&answer-1=34&answer-2=45`

**Comment by manki11** [comment]
Issue solved in 300b1b4e79bb6098765ff5b40de248ccbdd1bf52
