### ISSUE TITLE
Reopening Exercise from a not supported language fail translation

### ISSUE THREAD

**Issue by llaske** [manki11/ExerciserReact#3]
When an Exercise is reopen with a language not supported by the activity and different than the one used to create the Exercise, translation of some fields failed.

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/981841/44197858-207f6980-a140-11e8-922c-5d336b9ab358.png">

Steps to reproduce:
- Set your user language in Sugarizer to English
- Launch the activity
- Stop the activity
- Set your user language in Sugarizer to Polish
- Launch the activity again
- Fields {number} are not substituted correctly

Same issue when a shared Exercise is open from an unsupported translation language.
The expected result is that the activity use the default language (English).

**Comment by manki11** [comment]
Issue resolved in b5099a206e81f5d9990ec09fb76ff928de45c2d7
