### ISSUE TITLE
Title for toolbar buttons depend only of browser language

### ISSUE THREAD

**Issue by llaske** [manki11/ExerciserReact#4]
The title displayed on toolbar buttons depend only of browser language, not Sugarizer language.
In the following screen capture, the Sugarizer language is EN and the browser language is FR so title on "+" button appears in French instead of English.

![image](https://user-images.githubusercontent.com/981841/44406713-99c1f680-a55c-11e8-99f7-c26cf63c312d.png)

**Comment by manki11** [comment]
Issue was fixed in 846e7433f6dd79ddd9e2c5e8dc9e79ff94c43ef2
