### ISSUE TITLE
Exercise Id is not regenerated when using demo exercises

### ISSUE THREAD

**Issue by llaske** [manki11/ExerciserReact#8]
When using the demo exercises, the id is not correctly initialized so when an exercise is added or removed, the activity don't work correctly.

**Comment by manki11** [comment]
Whenever an increment is done in the amount of demo exercises. The initial state needs to be changed here to the id of the next exercise. https://github.com/manki11/ExerciserReact/blob/master/src/store/reducers/exercise_counter.js#L3

**Comment by manki11** [comment]
Issue solved in 95b1f0ccc23922e79c4b4f2dd3fdf549f82a0de6
